[tool.poetry]
name = "solutions"
version = "0.1.0"
description = ""
authors = ["Alexandru Constantin Cardas <calexc95@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.test.dependencies]
pytest-cov = "^4.0.0"
pytest-xdist = "^3.0.2"


[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^5.0.4"
pylint = "^2.15.5"
isort = "^5.10.1"
bandit = "^1.7.4"
mypy = "^0.982"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = "tests"
