{% set name = "solutions" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python
  build:
    - python
    - setuptools

about:
  home: The package home page
  license: BSD
  license_family: BSD
  license_file: LICENCE.md
  summary: "Composable command line interface toolkit"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - AlexandruCardas
